# Generated by Django 3.1.6 on 2022-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PsychHealapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='image',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
