# Generated by Django 3.1.6 on 2022-02-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PsychHealapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbies',
            name='hobbies',
        ),
    ]
