# Generated by Django 3.1.6 on 2022-02-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PsychHealapp', '0002_auto_20220213_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='exercise',
            new_name='medicine',
        ),
    ]
